services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: cwm_nginx_proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./docker/8.2/custom.conf:/etc/nginx/conf.d/custom.conf:ro
        networks:
            - sail
    cwm_api:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        container_name: cwm_api
        hostname: cwm_api
        expose:
            - 80
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            TZ: 'America/New_York'
            VIRTUAL_HOST: dev.api.cwm.com
            VIRTUAL_PORT: 80
        volumes:
            - '.:/var/www/html'
        networks:
            sail:
                aliases:
                    - "dev.api.cwm.com"
        depends_on:
            - cwm_mysql
            - cwm_redis
            - cwm_meilisearch
            - cwm_mailpit
            - cwm_selenium

    cwm_admin:
        image: node:latest
        environment:
            VIRTUAL_HOST: dev.admin.cwm.com
            VIRTUAL_PORT: 8080
        container_name: cwm_admin
        hostname: cwm_admin
        expose:
            - 8080
        volumes:
            - ../cwm_admin:/app
        working_dir: /app
        command: bash -c "npm install && npm run dev"
        networks:
            sail:
                aliases:
                    - "dev.admin.cwm.com"
        depends_on:
            - cwm_api

    cwm_app:
        image: node:latest
        environment:
            VIRTUAL_HOST: dev.app.cwm.com
            VIRTUAL_PORT: 8080
        container_name: cwm_app
        hostname: cwm_app
        expose:
            - 8080
        volumes:
            - ../cwm_app:/app
        working_dir: /app
        command: bash -c "npm install && npm run dev"
        networks:
            sail:
                aliases:
                    - "dev.app.cwm.com"
        depends_on:
            - cwm_api

    cwm_mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        container_name: cwm_mysql
        hostname: cwm_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'celebrateitwithme'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    cwm_redis:
        image: 'redis:alpine'
        container_name: cwm_redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    cwm_meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: cwm_meilisearch
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s
    cwm_mailpit:
        image: 'axllent/mailpit:latest'
        container_name: cwm_mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    cwm_selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
