#!/usr/bin/env bash

if [ "$EUID" -eq 0 ] && [ -f /usr/local/bin/fix-permissions ]; then
    /usr/local/bin/fix-permissions
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
